version: "1.0"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    image: httpserv-imge

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=http_serv
      - POSTGRES_PASS=http_pass
      - POSTGRES_DB=http_dc
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
